### ISSUE TITLE
Add ability to parse other file or stdin

### ISSUE THREAD

**Issue by phiresky** [hjr3/softnet-stat#2]
I'm trying to parse a saved file from a different server, but it looks like the /proc/net path is [hardcoded](https://github.com/hjr3/softnet-stat/blob/master/src/main.rs#L140). Would be great if this tool would also work on stdin or a supplied file.

(This project is the first result when searching google for "softnet stat")

**Comment by phiresky** [comment]
Thank you!

**Comment by hjr3** [comment]
@phiresky i merged support into the master branch. are you building from source or needing an rpm?

**Comment by phiresky** [comment]
I built it from source, so no package needed for me
